(function(){
const S=()=>LifePlusState.state;
const seed=[
['grocery','🛒','Продуктовий магазин',30000,'Торгівля продуктами'],['wash','🚿','Автомийка',50000,'Мийка автомобілів'],['cafe','🍔','Кафе',80000,'Їжа та напої'],['service','🔧','Автосервіс',100000,'Ремонт автомобілів'],['dealer','🚗','Автосалон',150000,'Продаж автомобілів']
];
const groups=[
['Торгівля','🛒',['Магазин одягу','Магазин взуття','Магазин електроніки','Магазин меблів','Магазин техніки','Магазин будматеріалів','Магазин косметики','Квітковий магазин','Магазин подарунків','Магазин спорттоварів','Зоомагазин','Магазин дитячих товарів','Книжковий магазин','Магазин автозапчастин','Супермаркет','Міні-маркет','Дискаунтер','Гіпермаркет']],
['Їжа','🍽️',['Піцерія','Бургерна','Пекарня','Кондитерська','Кав’ярня','Ресторан','Фастфуд','Суші-бар','Шашлична','Їдальня','Фудтрак','М’ясна крамниця','Рибний магазин','Магазин солодощів','Кейтеринг']],
['Авто','🚗',['Шиномонтаж','Магазин шин','Детейлінг','Мотосервіс','Евакуатор','Автозаправка','Прокат авто','Прокат велосипедів','Автоелектрик','Кузовний сервіс','Автофарбування','Автошкола']],
['Послуги','🧑‍💼',['Перукарня','Барбершоп','Салон краси','Манікюрний салон','Хімчистка','Пральня','Ательє','Ремонт телефонів','Ремонт техніки','Комп’ютерний сервіс','Фотоательє','Копіцентр','Друкарня','Турфірма','Рієлторська агенція','Клінінг','Сервіс доставки','Таксі-парк']],
['Відпочинок','🎮',['Фітнес-клуб','Спортзал','Йога-студія','Кінотеатр','Більярдний клуб','Боулінг','Ігровий клуб','Квест-кімната','Нічний клуб','Парк розваг','Дитячий центр','Басейн','Готель','Хостел','СПА-салон']],
['Великі','🏢',['Торговий центр','Бізнес-центр','Логістичний центр','Готельний комплекс','Мережа ресторанів','Мережа магазинів','Автомобільний холдинг','Приватна клініка','Приватна школа','Будівельна компанія','IT-компанія','Рекламна агенція','Виробниче підприємство','Складський комплекс','Фітнес-мережа','Мережа кав’ярень','Дистриб’юторська компанія']]
];
const biz=[...seed.map(x=>({type:x[0],icon:x[1],name:x[2],price:x[3],desc:x[4],cat:'Старт'}))];let n=0;groups.forEach((g,gi)=>g[2].forEach((name,i)=>{let price=gi<2?120000+i*28000:gi===2?180000+i*45000:gi===3?140000+i*35000:gi===4?250000+i*65000:gi===5?1500000+i*450000:100000;biz.push({type:'biz_'+(++n),icon:g[1],name,price,desc:g[0],cat:g[0]})}));
window.LifePlusPages.business={title:'🏢 Бізнеси',render:function(){const s=S();return `<section class="info-card"><div class="section-title">🏢 Мої бізнеси (${s.businesses.length})</div>${s.businesses.length?s.businesses.map(b=>`<div class="info-row"><span>${b.icon||'🏢'} ${b.name}</span><b>Власний</b></div><div class="info-row"><span>💰 Виручка</span><b>${LifePlusState.money(b.revenue||0)}</b></div><div class="info-row"><span>🛍️ Продажів</span><b>${b.sales||0}</b></div>`).join(''):`<div class="locked-home"><b>Бізнесів ще немає</b><small>Обери свій перший бізнес.</small></div>`}</section>${['Старт','Торгівля','Їжа','Авто','Послуги','Відпочинок','Великі'].map(cat=>{const list=biz.filter(x=>x.cat===cat);return `<section class="info-card"><div class="section-title">${cat==='Великі'?'🏢':cat==='Авто'?'🚗':cat==='Їжа'?'🍽️':cat==='Послуги'?'🧑‍💼':cat==='Відпочинок'?'🎮':'🛒'} ${cat} — ${list.length}</div>${list.map(b=>`<article class="job-card"><div class="job-icon">${b.icon}</div><div class="job-main"><b>${b.name}</b><small>${b.desc}</small><div class="job-meta"><span>💰 ${LifePlusState.money(b.price)}</span><span>📈 Без прокачки</span></div></div><button class="job-btn" data-biz="${b.type}">Купити</button></article>`).join('')}</section>`}).join('')}<section class="info-card"><div class="section-title">💰 Економіка бізнесу</div><div class="locked-home"><small>Гравець купує товар або послугу → гроші переходять власнику бізнесу. Для основних онлайн-бізнесів це вже проходить через сервер і Railway Volume.</small></div></section>`},bind:function(){document.querySelectorAll('[data-biz]').forEach(btn=>btn.onclick=()=>{const b=biz.find(x=>x.type===btn.dataset.biz),s=S();if(!b||s.balance<b.price)return LifePlusApp.toast('Недостатньо грошей');if(s.businesses.some(x=>x.type===b.type))return LifePlusApp.toast('Цей бізнес уже належить тобі');s.balance-=b.price;s.businesses.push({type:b.type,name:b.name,icon:b.icon,purchasePrice:b.price,revenue:0,sales:0,balance:0});LifePlusState.addHistory('Купівля бізнесу: '+b.name,'-'+LifePlusState.money(b.price));LifePlusState.addXP(20);LifePlusState.save();LifePlusApp.openPage('business',true)})}};
})();
