(function(){
const S=()=>LifePlusState.state;
const types=[['room','🛏️','Кімната',5000,1200,20],['dorm','🛏️','Гуртожиток',3500,800,15],['studio','🏠','Студія',7500,1400,30],['one','🏠','1-кімнатна квартира',10500,1800,40],['two','🏢','2-кімнатна квартира',15000,2300,50],['three','🏢','3-кімнатна квартира',22000,3000,60],['new1','🏙️','1-кімнатна в новобудові',15000,2400,55],['new2','🏙️','2-кімнатна в новобудові',23000,3200,65],['premium','🏙️','Преміум квартира',35000,4500,75],['pent','🌆','Пентхаус',65000,7000,90]];
const areas=['Центр','Північний','Ювілейний','Боярка','Автовокзал','Льонокомбінат','Новий Двір','Щасливе','Таїрове','Зелений район'];
const rentHomes=[];areas.forEach((a,ai)=>types.forEach((t,ti)=>rentHomes.push([t[0]+'_'+ai, t[1], t[2]+' • '+a, Math.round(t[3]*(1+ai*.035)+ti*300), Math.round(t[4]*(1+ai*.025)),t[5]+(ai%3)])));
const buyBase=[['flat1','🏠','Невелика квартира',650000,45],['flat2','🏢','2-кімнатна квартира',950000,55],['flat3','🏢','3-кімнатна квартира',1350000,65],['newflat','🏙️','Квартира в новобудові',1750000,72],['premiumflat','🌆','Преміум квартира',3200000,85],['house','🏡','Приватний будинок',1800000,70],['family','🏡','Сімейний будинок',2800000,78],['cottage','🏘️','Котедж',4500000,86],['villa','🏰','Вілла',9000000,94],['mansion','🏰','Особняк',18000000,100]];
const buyHomes=[];areas.forEach((a,ai)=>buyBase.forEach((h,hi)=>buyHomes.push([h[0]+'_'+ai,h[1],h[2]+' • '+a,Math.round(h[3]*(1+ai*.045)+hi*50000),h[4]+(ai%2)])));
window.LifePlusPages.housing={title:'🏠 Житло',render:function(){let s=S(),cur=[...rentHomes,...buyHomes].find(x=>x[0]===s.housing)||rentHomes[0],owned=s.housingOwned;return `<section class="info-card"><div class="section-title">🏠 Моє житло</div><div class="home-current"><div class="home-icon">${cur[1]}</div><div><b>${cur[2]}</b><small>${owned?'Власність':'Оренда'} • комфорт ${cur[5]||cur[4]}/100</small></div></div><div class="info-row"><span>💳 Щомісячна оренда</span><b>${owned?'₴0':LifePlusState.money(cur[3])}</b></div><div class="info-row"><span>💡 Комунальні</span><b>${owned?'за фактом':LifePlusState.money(Math.round((cur[4]||30)*35))+'/міс.'}</b></div><div class="info-row"><span>💸 Борг</span><b>${LifePlusState.money(s.debt)}</b></div></section><section class="info-card"><div class="section-title">🏠 Оренда — ${rentHomes.length} варіантів</div>${rentHomes.map(x=>`<article class="home-card"><div class="home-icon">${x[1]}</div><div class="home-main"><b>${x[2]}</b><small>Оренда • комфорт ${x[5]}/100</small><div class="home-meta"><span>💰 ${LifePlusState.money(x[3])}/міс.</span><span>💡 ${LifePlusState.money(x[4])}</span></div></div><button class="home-btn ${s.housing===x[0]&&!owned?'selected':''}" data-rent="${x[0]}">${s.housing===x[0]&&!owned?'Обрано':'Орендувати'}</button></article>`).join('')}</section><section class="info-card"><div class="section-title">🏡 Купівля — ${buyHomes.length} варіантів</div>${buyHomes.map(x=>`<article class="home-card"><div class="home-icon">${x[1]}</div><div class="home-main"><b>${x[2]}</b><small>Власність • комфорт ${x[4]}/100</small><div class="home-meta"><span>💰 ${LifePlusState.money(x[3])}</span><span>🏠 назавжди</span></div></div><button class="home-btn ${s.housing===x[0]&&owned?'selected':''}" data-buyhome="${x[0]}">${s.housing===x[0]&&owned?'Власне':'Купити'}</button></article>`).join('')}</section>`},bind:function(){document.querySelectorAll('[data-rent]').forEach(b=>b.onclick=()=>{const x=rentHomes.find(h=>h[0]===b.dataset.rent);if(!x)return;S().housing=x[0];S().housingOwned=false;LifePlusState.save();LifePlusApp.openPage('housing',true)});document.querySelectorAll('[data-buyhome]').forEach(b=>b.onclick=()=>{const x=buyHomes.find(h=>h[0]===b.dataset.buyhome),s=S();if(!x||s.balance<x[3])return LifePlusApp.toast('Недостатньо грошей');s.balance-=x[3];s.housing=x[0];s.housingOwned=true;LifePlusState.addHistory('Купівля житла','-'+LifePlusState.money(x[3]));LifePlusState.addXP(25);LifePlusState.save();LifePlusApp.openPage('housing',true)})}};
})();
