(function(){
const S=()=>LifePlusState.state;
const cars=[
 ["lada","🚗","Lada 2107",8000],
 ["lanos","🚙","Daewoo Lanos",12000],
 ["octavia","🚘","Skoda Octavia",25000]
];
function carData(c){return {fuel:c.fuel===undefined?100:c.fuel,condition:c.condition===undefined?100:c.condition,price:c.price||0}}
function bar(v){return `<div style="font-size:12px;margin-top:5px">${Math.round(v)}%</div>`}
window.LifePlusPages.transport={title:"🚗 Транспорт",render:function(){
 let s=S(),dealer=LifePlusState.ownedBusiness("dealer"),service=LifePlusState.ownedBusiness("service");
 return `<section class="info-card"><div class="section-title">🚗 Мій гараж</div>${s.cars.length?s.cars.map((c,i)=>{let d=carData(c);return `<article class="job-card"><div class="job-icon">${c.icon}</div><div class="job-main"><b>${c.name}</b><small>⛽ Паливо ${bar(d.fuel)} · 🛠️ Стан ${bar(d.condition)}</small><div class="job-meta"><span>💰 Куплено за ${LifePlusState.money(d.price)}</span></div></div><div style="display:flex;gap:6px;flex-wrap:wrap"><button class="job-btn" data-trip="${i}">Поїхати</button><button class="job-btn" data-fuel="${i}">⛽</button><button class="job-btn" data-repair="${i}">🔧</button><button class="job-btn" data-sell="${i}">Продати</button></div></article>`}).join(""):`<div class="locked-home"><b>Гараж порожній</b><small>Придбай свій перший автомобіль.</small></div>`}</section>
 ${service?`<section class="info-card"><div class="section-title">🔧 Твій автосервіс</div><div class="info-row"><span>Виручка</span><b>${LifePlusState.money(service.revenue||0)}</b></div><div class="info-row"><span>Ремонтів</span><b>${service.sales||0}</b></div></section>`:""}
 <section class="info-card"><div class="section-title">🚘 Автомобілі у продажу</div>${cars.map(c=>`<article class="job-card"><div class="job-icon">${c[1]}</div><div class="job-main"><b>${c[2]}</b><small>${dealer?"Купівля в твоєму автосалоні":"Автомобіль у продажу"}</small><div class="job-meta"><span>💰 ${LifePlusState.money(c[3])}</span></div></div><button class="job-btn" data-car="${c[0]}">Купити</button></article>`).join("")}</section>`
},bind:function(){
 document.querySelectorAll("[data-car]").forEach(b=>b.onclick=async()=>{const c=cars.find(x=>x[0]===b.dataset.car),s=S();if(!c||s.balance<c[3])return LifePlusApp.toast("Недостатньо грошей");b.disabled=true;try{const dealer=LifePlusState.ownedBusiness("dealer");if(dealer&&window.LifePlusAPI){const r=await LifePlusAPI.purchaseFromBusiness("dealer",c[2],c[3]);Object.assign(s,r.buyerState);s.cars.push({name:c[2],icon:c[1],price:c[3],fuel:100,condition:100});s.tasks.firstCar=true;LifePlusState.save();LifePlusApp.toast("Автомобіль куплено у гравця")}else{s.balance-=c[3];s.cars.push({name:c[2],icon:c[1],price:c[3],fuel:100,condition:100});s.tasks.firstCar=true;if(dealer){dealer.revenue=(dealer.revenue||0)+c[3];dealer.sales=(dealer.sales||0)+1;dealer.balance=(dealer.balance||0)+c[3];LifePlusState.addHistory("Продаж авто через твій автосалон","+"+LifePlusState.money(c[3]))}else LifePlusState.addHistory("Купівля авто","-"+LifePlusState.money(c[3]));LifePlusState.save()}LifePlusApp.openPage("transport",true)}catch(e){b.disabled=false;LifePlusApp.toast(e.message)}});
 document.querySelectorAll("[data-trip]").forEach(b=>b.onclick=()=>{const c=S().cars[Number(b.dataset.trip)],d=carData(c);if(!c)return;if(d.fuel<10)return LifePlusApp.toast("Потрібно заправити авто");c.fuel=Math.max(0,d.fuel-10);c.condition=Math.max(0,d.condition-2);LifePlusState.addHistory("Поїздка на авто","-10% пального");LifePlusState.save();LifePlusApp.openPage("transport",true)});
 document.querySelectorAll("[data-fuel]").forEach(b=>b.onclick=()=>{const c=S().cars[Number(b.dataset.fuel)],d=carData(c),cost=500;if(!c||d.fuel>=100)return LifePlusApp.toast("Бак вже повний");if(S().balance<cost)return LifePlusApp.toast("Недостатньо грошей");c.fuel=100;S().balance-=cost;LifePlusState.addHistory("Заправка авто","-"+LifePlusState.money(cost));LifePlusState.save();LifePlusApp.openPage("transport",true)});
 document.querySelectorAll("[data-repair]").forEach(b=>b.onclick=()=>{const c=S().cars[Number(b.dataset.repair)],d=carData(c),cost=800;if(!c||d.condition>=100)return LifePlusApp.toast("Авто не потребує ремонту");if(S().balance<cost)return LifePlusApp.toast("Недостатньо грошей");c.condition=100;S().balance-=cost;const service=LifePlusState.ownedBusiness("service");if(service){service.revenue=(service.revenue||0)+cost;service.sales=(service.sales||0)+1;service.balance=(service.balance||0)+cost;LifePlusState.addHistory("Ремонт у твоєму автосервісі","+"+LifePlusState.money(cost))}else LifePlusState.addHistory("Ремонт авто","-"+LifePlusState.money(cost));LifePlusState.save();LifePlusApp.openPage("transport",true)});
 document.querySelectorAll("[data-sell]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.sell),c=S().cars[i];if(!c)return;const price=Math.floor((c.price||0)*0.7);S().cars.splice(i,1);S().balance+=price;LifePlusState.addHistory("Продаж автомобіля","+"+LifePlusState.money(price));LifePlusState.save();LifePlusApp.openPage("transport",true)});
}}
})();