(function(){
const S=()=>LifePlusState.state;
function fmt(ms){let sec=Math.max(0,Math.floor(ms/1000)),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return [h,m,s].map(v=>String(v).padStart(2,'0')).join(':')}
const groups=[
[1,[['📦','Працівник складу',18000],['🛒','Касир',20000],['🧹','Прибиральник',18000],['🚴','Кур’єр',22000],['🍽️','Працівник кафе',20000],['🧑‍💼','Продавець',21000],['☎️','Оператор кол-центру',23000],['⛽','Заправник',22000],['📦','Пакувальник',19000],['🚿','Мийник авто',21000],['🧺','Працівник пральні',20000],['🛍️','Працівник супермаркету',22000],['📮','Працівник пошти',23000],['🍔','Працівник фастфуду',22000],['🧑‍🌾','Різноробочий',24000]]],
[2,[['🚕','Водій таксі',28000],['🚚','Водій доставки',30000],['🛡️','Охоронець',27000],['👨‍🍳','Кухар',32000],['☕','Бариста',27000],['✂️','Перукар',30000],['🧑‍💼','Адміністратор',32000],['🔧','Механік',34000],['⚡','Електрик',36000],['🚰','Сантехнік',35000],['🏗️','Будівельник',36000],['🎨','Маляр',32000],['🔥','Зварювальник',40000],['🏭','Оператор виробництва',35000],['📦','Комірник',30000],['📡','Диспетчер',33000],['🛍️','Продавець-консультант',31000],['🏠','Рієлтор',38000],['📷','Фотограф',35000],['🧁','Кондитер',36000]]],
[3,[['💻','Програміст',60000],['🌐','Веброзробник',58000],['🎨','Дизайнер',48000],['📊','Бухгалтер',50000],['📈','Економіст',52000],['📣','Маркетолог',50000],['🚛','Логіст',52000],['⚙️','Інженер',62000],['🔧','Автомеханік',50000],['🧪','Лаборант',48000],['🖥️','Системний адміністратор',55000],['🎬','Відеомонтажер',50000],['🧊','3D-моделер',58000],['🏛️','Архітектор',70000],['⚖️','Юрист',65000],['👥','HR-менеджер',52000],['💹','Фінансовий аналітик',68000],['📋','Менеджер проєктів',65000],['💱','Брокер',72000],['🧑‍⚕️','Фармацевт',50000],['🩺','Медсестра',42000],['🚑','Фельдшер',50000],['👨‍🏫','Вчитель',42000],['🎤','Журналіст',45000],['🎥','Оператор',48000]]],
[4,[['🧑‍💻','Senior-програміст',85000],['☁️','DevOps-спеціаліст',90000],['🛡️','Кібербезпекар',95000],['🧾','Головний бухгалтер',85000],['💰','Фінансовий менеджер',90000],['🏗️','Інженер-проєктувальник',88000],['🎮','Game Developer',80000],['🧠','Data Analyst',82000],['🎨','Артдиректор',78000],['👔','Керівник відділу',95000],['🏪','Директор магазину',85000],['🍽️','Директор ресторану',90000],['🚛','Керівник логістики',92000],['🔩','Головний механік',80000],['⚖️','Старший юрист',90000],['📈','Інвестиційний аналітик',100000],['🏥','Лікар',85000],['🦷','Стоматолог',95000],['🏫','Директор школи',85000],['🎬','Продюсер',80000]]],
[5,[['🏢','Директор компанії',150000],['💰','Фінансовий директор',180000],['⚙️','Операційний директор',170000],['💻','IT-директор',180000],['📣','Комерційний директор',160000],['🚗','Директор автосалону',150000],['🛍️','Директор мережі магазинів',170000],['🏭','Керівник підприємства',180000],['🏨','Генеральний менеджер',150000],['🌍','Регіональний директор',190000],['🏦','Директор банківського відділення',170000],['📊','Директор з розвитку',165000]]],
[6,[['👑','CEO',300000],['💻','CTO',320000],['💰','CFO',330000],['🏢','Керівник корпорації',400000],['📈','Інвестиційний директор',350000],['🌐','Корпоративний консультант',280000],['🚀','Топовий IT-фахівець',350000],['🏦','Керівник великої мережі',380000],['🏭','Генеральний директор холдингу',450000],['💼','Партнер великої компанії',500000]]]
];
function effectivePay(monthly){return Math.floor(monthly/30*(1+Math.min(.25,Math.floor(S().workedHours/10)*.025)))}
function jobCard(j,career,s){const level=j[0],icon=j[1],name=j[2],monthly=j[3],locked=level>career.level;return '<article class="job-card"><div class="job-icon">'+icon+'</div><div class="job-main"><b>'+name+'</b><small>'+(locked?'🔒 Потрібен кар’єрний рівень '+level:'Доступно • '+LifePlusState.money(monthly)+'/міс.')+'</small><div class="job-meta"><span>💰 '+LifePlusState.money(effectivePay(monthly))+' / зміна</span><span>⏱️ 1 год.</span></div></div><button class="job-btn" data-job-level="'+level+'" data-job-name="'+name.replace(/"/g,'&quot;')+'" data-job-icon="'+icon+'" data-job-monthly="'+monthly+'" '+(locked?'disabled':'')+'>'+(s.job&&s.job.name===name?'Обрано':'Обрати')+'</button></article>'}
window.LifePlusPages.work={title:'💼 Робота',render:function(){let s=S(),career=s.career||{level:1};let html='<section class="info-card"><div class="section-title">Поточна робота</div><div class="job-current"><b>'+(s.job?s.job.name:'Без роботи')+'</b><small>'+(s.job?'Кар’єрний рівень '+s.job.level+' • '+LifePlusState.money(s.job.monthly)+'/міс.':'Обери професію')+'</small>'+(s.working?'<div class="job-timer" id="shiftTimer">'+fmt(s.shiftEndsAt-Date.now())+'</div><button class="job-btn" id="leaveWork">Завершити раніше</button>':'<button class="job-btn" id="startWork">▶️ Почати зміну</button>')+'</div></section><section class="info-card"><div class="section-title">📈 Кар’єра</div><div class="info-row"><span>⭐ Рівень кар’єри</span><b>'+career.level+'/6</b></div><div class="info-row"><span>⏱️ Відпрацьовано</span><b>'+s.workedHours.toFixed(1)+' год.</b></div><div class="info-row"><span>⬆️ Підвищень</span><b>'+(career.promotions||0)+'</b></div></section>';
groups.forEach(g=>{html+='<section class="info-card"><div class="section-title">'+(g[0]===1?'🟢':g[0]===2?'🔵':g[0]===3?'🟣':g[0]===4?'🟠':g[0]===5?'🔴':'👑')+' Рівень '+g[0]+'</div>';g[1].forEach(j=>html+=jobCard(j,career,s));html+='</section>'});return html},bind:function(){let s=S();document.querySelectorAll('[data-job-name]').forEach(b=>b.onclick=()=>{if(s.working)return;const j={level:+b.dataset.jobLevel,name:b.dataset.jobName,icon:b.dataset.jobIcon,monthly:+b.dataset.jobMonthly};s.job=j;s.tasks.firstJob=true;LifePlusState.addXP(10);LifePlusState.save();LifePlusApp.openPage('work',true)});const st=document.getElementById('startWork');if(st)st.onclick=()=>{if(!s.job)return LifePlusApp.toast('Спочатку обери професію');s.working=true;s.shiftStartedAt=Date.now();s.shiftEndsAt=Date.now()+3600000;s.shiftPay=effectivePay(s.job.monthly);LifePlusState.save();LifePlusApp.openPage('work',true)};const leave=document.getElementById('leaveWork');if(leave)leave.onclick=()=>{let ratio=Math.min(1,Math.max(0,(Date.now()-s.shiftStartedAt)/3600000)),pay=Math.floor(s.shiftPay*ratio);s.balance+=pay;s.workedHours+=ratio;s.daily.earned=(s.daily.earned||0)+pay;s.weekly.earned=(s.weekly.earned||0)+pay;s.weekly.worked=(s.weekly.worked||0)+ratio;if(ratio>=.99){s.daily.shift=true;s.weekly.worked=Math.max(s.weekly.worked,1)}s.working=false;s.shiftStartedAt=s.shiftEndsAt=s.shiftPay=0;LifePlusState.addXP(Math.max(1,Math.floor(25*ratio)));LifePlusState.addHistory('Зарплата','+'+LifePlusState.money(pay));let newLevel=Math.min(6,Math.floor(s.workedHours/20)+1);if(newLevel>s.career.level){s.career.level=newLevel;s.career.promotions++;LifePlusApp.toast('🎉 Підвищення до кар’єрного рівня '+newLevel)}LifePlusState.save();LifePlusApp.toast('Отримано '+LifePlusState.money(pay));LifePlusApp.openPage('work',true)};if(s.working){clearInterval(window.lifeWorkTimer);window.lifeWorkTimer=setInterval(()=>{const e=document.getElementById('shiftTimer');if(e)e.textContent=fmt(s.shiftEndsAt-Date.now())},1000)}}};
})();
